title: YoinkBird
description: Automation from Bare Metal to the Cloud!

# https://github.com/pages-themes/midnight?tab=readme-ov-file
remote_theme: pages-themes/midnight@v0.2.0

plugins:
- jekyll-remote-theme
