#
title: TODO DEV YoinkBird DEV TODO
description: TODO DEV Automation from Bare Metal to the Cloud! DEV TODO

# https://stackoverflow.com/questions/27386169/change-site-url-to-localhost-during-jekyll-local-development
# https://stackoverflow.com/questions/79722190/jekyll-generates-urls-with-0-0-0-0
# host: 0.0.0.0
# host: localhost
# url: ""
# url: http://localhost

liquid:
  # https://jekyllrb.com/docs/configuration/liquid/
  # CAVEAT: this did not work well; it's as silly as 'bash -eu' in that even _checking_ if a var is defined will cause an error
  # error_mode: strict
  # strict_variables: true
  # strict_filters: true


plugins:
# allowed plugins: 
#  https://pages.github.com/versions.json
#  https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
# - jekyll-mermaid
#
# mermaid:
#   src: 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'

#TODO - jekyll-spaceship
# jekyll-spaceship:
# https://github.com/jeffreytse/jekyll-spaceship?tab=readme-ov-file#installation
# # https://github.com/jeffreytse/jekyll-spaceship?tab=readme-ov-file#configuration
# # Where things are
#   # default enabled processors
#   processors:
#     - table-processor
#     - mathjax-processor
#     - plantuml-processor
#     - mermaid-processor
#     - polyfill-processor
#     - media-processor
#     - emoji-processor
#     - element-processor
#   mathjax-processor:
#     src:
#       - https://polyfill.io/v3/polyfill.min.js?features=es6
#       - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#     config:
#       tex:
#         inlineMath:
#           - ['$','$']
#           - ['\(','\)']
#         displayMath:
#           - ['$$','$$']
#           - ['\[','\]']
#       svg:
#         fontCache: 'global'
#     optimize: # optimization on building stage to check and add mathjax scripts
#       enabled: true # value `false` for adding to all pages
#       include: []   # include patterns for math expressions checking (regexp)
#       exclude: []   # exclude patterns for math expressions checking (regexp)
#   plantuml-processor:
#     mode: default  # mode value 'pre-fetch' for fetching image at building stage
#     css:
#       class: plantuml
#     syntax:
#       code: 'plantuml!'
#       custom: ['@startuml', '@enduml']
#     src: http://www.plantuml.com/plantuml/svg/
#   mermaid-processor:
#     mode: default  # mode value 'pre-fetch' for fetching image at building stage
#     css:
#       class: mermaid
#     syntax:
#       code: 'mermaid!'
#       custom: ['@startmermaid', '@endmermaid']
#     config:
#       theme: default
#     src: https://mermaid.ink/svg/
#   media-processor:
#     default:
#       id: 'media-{id}'
#       class: 'media'
#       width: '100%'
#       height: 350
#       frameborder: 0
#       style: 'max-width: 600px; outline: none;'
#       allow: 'encrypted-media; picture-in-picture'
#   emoji-processor:
#     css:
#       class: emoji
#     src: https://github.githubassets.com/images/icons/emoji/
